### ISSUE TITLE
Error with double values

### ISSUE THREAD

**Issue by rperaza** [mburge/imagingbook#1]
After compiling the Bilinear Interpolator, there were 8 errors for the double values including the ip,getPixelValue().  Is this normal or is this example not meant to complie?

**Comment by mburge** [comment]
Please see https://bitbucket.org/imagingbook/imagingbook-public - this is an old version which I'm going to remove and replace with a redirect.

**Comment by rperaza** [comment]
What's the main difference between the redirect and the old one?

**Comment by mburge** [comment]
The redirect is the current version. There are many differences. Take a
look at the log files at the other site.
